// AUTO-GENERATED by scripts/build-case-decks.sh — do not edit by hand.
export type CaseDeck = { label: string; pages: number; dir: string };

export const CASE_DECKS: Record<string, CaseDeck> = {
  "cardo": { label: "Business Report", pages: 52, dir: "/case-pdf/cardo" },
  "aid-sirho-frames": { label: "Portfolio", pages: 10, dir: "/case-pdf/aid-sirho-frames" },
  "cuttleswish": { label: "Group Portfolio", pages: 23, dir: "/case-pdf/cuttleswish" },
  "brushed-lips": { label: "SDE Report", pages: 14, dir: "/case-pdf/brushed-lips" },
};
