// AUTO-GENERATED by scripts/build-case-decks.sh + extract-deck-titles.py
// — do not edit by hand.
export type CaseDeck = {
  label: string;
  pages: number;
  dir: string;
  /** Section title per page, where one could be detected. */
  titles: (string | null)[];
};

export const CASE_DECKS: Record<string, CaseDeck> = {
  "cardo": { label: "Business Report", pages: 52, dir: "/case-pdf/cardo", titles: ["Business Report", null, null, "Problem", "The process", "Revolut Budgeting", "Table 2.2.1 Competitor Landscape", "ST", "Table 2.5.1 Internal Risks", "Table 2.6.1 External Risks", "Stage 1", "KEY STRESSES", "WEAKNESSES", "Table 3.3.1: Concept", "Key Features", "Believe they would find", "Young Professional at Unilever", "Budge", "Processes", null, "Value Proposition Canvas - Consumers", "TAM", "ADRESSABLE MARKET", "Market Scope Assumptions", "Key Partners", "Young Professionals (20-35)", "Subscription revenue(Freemium model)", "Most banks keep 10% aggregate", "Initial roll-out in London (year 1", "Crowdfunds £1M In", "Revenue Diversification", "Solution", "Impact: R", "The electrochromic card can", "Additionally, webinars help us to directly", "Co", "Co", "Cost Breakdow", "See full P&L spreadsheet here", "Table 9.1.3.1: App Services Costs", "Setup Costs", "Table 9.4.1:Revenue Breakdown", "Acquisition Cost (CAC)", "Table 9.5.4.1: BAC Annual Weighting", "P&L(£)", "References", null, null, null, null, "Estimating data insights value", "Reach"] },
  "aid-sirho-frames": { label: "Portfolio", pages: 10, dir: "/case-pdf/aid-sirho-frames", titles: ["Sinai Rhodes", "Voronoi Structured Mesh", "Universal Wheel", "Ilaria Di Maio", "Morphological analysis", null, "Voronoi Generation", "CMF.", null, "Isolated on an orange-tinted gradient"] },
  "cuttleswish": { label: "Group Portfolio", pages: 23, dir: "/case-pdf/cuttleswish", titles: [null, "CONCEPT DEVELOPMENT", "CONCEPT DEVELOPMENT", "CONCEPT DEVELOPMENT", "COLOURS, MATERIALS & FINISHES", "DETAIL DESIGN", "DETAIL DESIGN", "BRANDING CONSIDERATIONS", "BRANDING IMPLEMENTATION", "PRODUCT ASSEMBLY PROCESS", "SYSTEM ARCHITECTURE", "PRODUCT COMPLIANCE", "EXPLODED VIEW", "PRODUCT LABELLING", "USER GUIDE DESIGN", "PACKAGING DESIGN", null, null, null, "PROJECT PLAN", "CUTTLESWISH", "CUTTLESWISH", "CUTTLESWISH"] },
  "brushed-lips": { label: "SDE Report", pages: 14, dir: "/case-pdf/brushed-lips", titles: [null, null, null, null, null, null, null, null, null, null, null, null, null, null] },
};
