// AUTO-GENERATED by scripts/build-work-assets.sh — do not edit by hand.
export type WorkImage = {
  src: string;
  alpha: boolean;
  w: number;
  h: number;
  /** UI / screen captures: sit on white, not the dark ground. */
  light?: boolean;
  /** Span the full collage row rather than the cycling rhythm. */
  full?: boolean;
  /** Extra white margin around a cut-out on its light ground. */
  padded?: boolean;
  /** Explicit 12-col span, overriding the cycling rhythm. */
  span?: number;
  /** Centre the figure in its row rather than letting it sit left. */
  centred?: boolean;
  /** Sit on Cardo's own warm ground rather than the default white. */
  beige?: boolean;
};

export const WORK_MEDIA: Record<
  string,
  { hero: WorkImage; collage: WorkImage[] }
> = {
  "interax": {
    hero: { src: "/work/interax/hero.jpg", alpha: false, w: 1800, h: 1260 },
    collage: [
      { src: "/work/interax/c1.png", alpha: true, w: 1800, h: 1012 , light: true },
      { src: "/work/interax/c2.png", alpha: true, w: 1490, h: 555, light: true },
      { src: "/work/interax/c3.png", alpha: true, w: 1739, h: 1012 , light: true },
      { src: "/work/interax/c4.png", alpha: false, w: 1800, h: 1225, light: true, full: true },
    ],
  },
  "cardo": {
    hero: { src: "/work/cardo/hero.jpg", alpha: false, w: 1800, h: 1237 },
    collage: [
      { src: "/work/cardo/c2.png", alpha: true, w: 1749, h: 487, light: true, padded: true, beige: true },
    ],
  },
  "aid-sirho-frames": {
    hero: { src: "/work/aid-sirho-frames/hero.jpg", alpha: false, w: 1800, h: 1086 },
    collage: [
      { src: "/work/aid-sirho-frames/c2.jpg", alpha: false, w: 1800, h: 1121 },
      { src: "/work/aid-sirho-frames/c3.png", alpha: false, w: 1800, h: 1038 },
      { src: "/work/aid-sirho-frames/c4.png", alpha: false, w: 1800, h: 1273 },
    ],
  },
  "cuttleswish": {
    hero: { src: "/work/cuttleswish/hero.jpg", alpha: false, w: 1800, h: 1212 },
    collage: [
      { src: "/work/cuttleswish/c1.jpg", alpha: false, w: 1800, h: 1200 },
      { src: "/work/cuttleswish/c2.png", alpha: false, w: 499, h: 402, span: 4 },
      { src: "/work/cuttleswish/c3.jpg", alpha: false, w: 1800, h: 1200, span: 8 },
      { src: "/work/cuttleswish/c4.png", alpha: false, w: 1800, h: 1243, full: true },
    ],
  },
  "brushed-lips": {
    hero: { src: "/work/brushed-lips/hero.jpg", alpha: false, w: 1600, h: 572 },
    collage: [
      { src: "/work/brushed-lips/c2.png", alpha: false, w: 1800, h: 962 },
    ],
  },
  "verdure": {
    hero: { src: "/work/verdure/hero.jpg", alpha: false, w: 1800, h: 1205 },
    collage: [
      { src: "/work/verdure/c1.jpg", alpha: false, w: 1339, h: 2000 },
      { src: "/work/verdure/c2.jpg", alpha: false, w: 1800, h: 1205 },
      { src: "/work/verdure/c3.jpg", alpha: false, w: 1800, h: 1205 },
    ],
  },
};
