#!/usr/bin/env bash
# Rasterise each project's source PDF into web-sized JPEG pages for the
# on-site slideshow, and generate lib/case-decks.ts.
#
# The source PDFs are 31-161MB each — far too large to hand a browser —
# so pages are rendered once here at 1400px wide, quality 80.
#
# Requires poppler's pdftoppm/pdfinfo.
# Usage: bash scripts/build-case-decks.sh
set -euo pipefail
cd "$(dirname "$0")/.."

OUT_TS="lib/case-decks.ts"
WIDTH=1400
QUALITY=80

# slug|source pdf|human label
DECKS=(
  "cardo|raw-assets/cardo/project-work/Cardo - Business Report.pdf|Business Report"
  "sirho-frames|raw-assets/aid/project-work/Rhodes_Sinai_Portfolio.pdf|Portfolio"
  "cuttleswish|raw-assets/cuttleswish/project-work/IDE_Group4_Portfolio.pdf|Group Portfolio"
  "brushed-lips|raw-assets/brushed-lips/project-work/SDE.pdf|SDE Report"
)

{
  echo "// AUTO-GENERATED by scripts/build-case-decks.sh — do not edit by hand."
  echo "export type CaseDeck = { label: string; pages: number; dir: string };"
  echo ""
  echo "export const CASE_DECKS: Record<string, CaseDeck> = {"
} > "$OUT_TS"

for row in "${DECKS[@]}"; do
  slug="${row%%|*}"
  rest="${row#*|}"
  src="${rest%%|*}"
  label="${rest##*|}"

  if [[ ! -f "$src" ]]; then
    echo "SKIP $slug — missing $src" >&2
    continue
  fi

  dir="public/case-pdf/$slug"
  rm -rf "$dir"; mkdir -p "$dir"
  pdftoppm -jpeg -jpegopt "quality=$QUALITY" -scale-to-x "$WIDTH" -scale-to-y -1 \
    "$src" "$dir/p"
  count=$(find "$dir" -name "p-*.jpg" | wc -l | tr -d ' ')
  # pdftoppm zero-pads to the page-count width; normalise to p1.jpg…pN.jpg
  i=1
  for f in $(find "$dir" -name "p-*.jpg" | sort); do
    mv "$f" "$dir/p$i.jpg"
    i=$((i + 1))
  done

  echo "  \"$slug\": { label: \"$label\", pages: $count, dir: \"/case-pdf/$slug\" }," >> "$OUT_TS"
  echo "built $slug — $count pages ($(du -sh "$dir" | cut -f1))"
done

echo "};" >> "$OUT_TS"
echo "wrote $OUT_TS"
