#!/usr/bin/env bash
# Discover per-project Hero-* and numeric-prefixed images in raw-assets/,
# optimise them into public/work/<slug>/ (longest edge 1800px; alpha stays
# PNG, opaque becomes JPEG 82), and generate lib/work-images.ts recording
# src, alpha and dimensions for layout decisions (transparent PNGs get
# white boxes in the /work collage).
#
# Usage: bash scripts/build-work-assets.sh
set -euo pipefail
cd "$(dirname "$0")/.."

MAX=1800
OUT_TS="lib/work-images.ts"

# raw-assets dir → site slug, in site project order
DIRS=(interax cardo aid cuttleswish brushed-lips verdure)
slug_for() {
  case "$1" in
    aid) echo "aid-sirho-frames" ;;
    *) echo "$1" ;;
  esac
}

process() { # $1 src, $2 dest-base (no ext) → echoes "src|alpha|w|h"
  local src="$1" dest_base="$2"
  local width height alpha longest dest
  width=$(sips -g pixelWidth "$src" | awk '/pixelWidth/{print $2}')
  height=$(sips -g pixelHeight "$src" | awk '/pixelHeight/{print $2}')
  alpha=$(sips -g hasAlpha "$src" | awk '/hasAlpha/{print $2}')
  longest=$(( width > height ? width : height ))
  local fmt_args=()
  if [[ "$alpha" == "yes" ]]; then
    dest="$dest_base.png"; fmt_args=(-s format png)
  else
    dest="$dest_base.jpg"; fmt_args=(-s format jpeg -s formatOptions 82)
  fi
  if (( longest > MAX )); then
    sips "${fmt_args[@]}" --resampleHeightWidthMax "$MAX" "$src" --out "$dest" >/dev/null
  else
    sips "${fmt_args[@]}" "$src" --out "$dest" >/dev/null
  fi
  local ow oh
  ow=$(sips -g pixelWidth "$dest" | awk '/pixelWidth/{print $2}')
  oh=$(sips -g pixelHeight "$dest" | awk '/pixelHeight/{print $2}')
  echo "/${dest#public/}|$alpha|$ow|$oh"
}

ts_entry() { # "src|alpha|w|h" → TS object literal
  IFS='|' read -r src alpha w h <<< "$1"
  local a="false"; [[ "$alpha" == "yes" ]] && a="true"
  echo "{ src: \"$src\", alpha: $a, w: $w, h: $h }"
}

{
  echo "// AUTO-GENERATED by scripts/build-work-assets.sh — do not edit by hand."
  echo "export type WorkImage = { src: string; alpha: boolean; w: number; h: number };"
  echo ""
  echo "export const WORK_MEDIA: Record<"
  echo "  string,"
  echo "  { hero: WorkImage; collage: WorkImage[] }"
  echo "> = {"
} > "$OUT_TS"

for dir in "${DIRS[@]}"; do
  slug=$(slug_for "$dir")
  outdir="public/work/$slug"
  mkdir -p "$outdir"

  hero_src=$(find "raw-assets/$dir" -type f -name "Hero-*" ! -name ".DS_Store" | head -1)
  [[ -z "$hero_src" ]] && { echo "ERROR: no Hero-* image for $dir" >&2; exit 1; }
  hero_info=$(process "$hero_src" "$outdir/hero")

  echo "  \"$slug\": {" >> "$OUT_TS"
  echo "    hero: $(ts_entry "$hero_info")," >> "$OUT_TS"
  echo "    collage: [" >> "$OUT_TS"

  # Numeric-prefixed files anywhere under the project dir, numeric order.
  while IFS= read -r line; do
    src="${line#*|}"
    n="${line%%|*}"
    info=$(process "$src" "$outdir/c$n")
    echo "      $(ts_entry "$info")," >> "$OUT_TS"
  done < <(
    find "raw-assets/$dir" -type f ! -name ".DS_Store" |
      awk -F/ '{ f=$NF; if (f ~ /^[0-9]+-/) { split(f, a, "-"); printf "%d|%s\n", a[1], $0 } }' |
      sort -t'|' -k1,1n
  )

  echo "    ]," >> "$OUT_TS"
  echo "  }," >> "$OUT_TS"
  echo "built: $slug"
done

echo "};" >> "$OUT_TS"
echo "wrote $OUT_TS"
