#!/usr/bin/env python3
"""Pull a section title for each page of the deck PDFs using pdftotext,
and fold them into lib/case-decks.ts so the slideshow progress bar can
label real content sections instead of bare page numbers.

Heuristic: the first short, title-like line on each page. Pages with no
plausible heading fall back to null (the UI shows the page number).

Usage: python3 scripts/extract-deck-titles.py
"""
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TS = ROOT / "lib" / "case-decks.ts"

SOURCES = {
    "interax": "raw-assets/interax/web-ready-assets/project-work/interax-portfolio.pdf",
    "cardo": "raw-assets/cardo/project-work/Cardo - Business Report.pdf",
    "aid-sirho-frames": "raw-assets/aid/project-work/Rhodes_Sinai_Portfolio.pdf",
    "cuttleswish": "raw-assets/cuttleswish/project-work/IDE_Group4_Portfolio.pdf",
    "brushed-lips": "raw-assets/brushed-lips/project-work/SDE.pdf",
}

# Lines that are page furniture rather than section titles.
NOISE = re.compile(
    r"^(page\s*\d+|\d+|figure\s*\d+|fig\.?\s*\d+|contents|www\.|http)",
    re.I,
)

# Team documents carry a per-page author byline in the same type size as a
# heading, so the first "title-like" line on a page is sometimes just a
# name. Skipped from page 2 onward only: a cover page's title genuinely
# can be the author's name (Sirho Frames' portfolio opens on exactly
# that).
BYLINES = {
    "ashley yang",
    "gexing fang",
    "ruby kennedy",
    "sinai rhodes",
    "freddie nicholson",
    "emmanuel irechukwu",
    "liberty wright",
    "kaitai yang",
    "francesco",
    "alex",
}

# Some headings are split across lines by the layout, or set in a face
# whose runs pdftotext returns out of order, so the first title-like line
# is only a fragment. These are read off the page and pinned here, so a
# re-run of this script does not undo them.
OVERRIDES: dict[str, dict[int, str]] = {
    "brushed-lips": {
        2: "PROBLEM OUTLINE",
        3: "FUTURE SCENARIO",
        12: "VALUE SYSTEM OVERVIEW",
        13: "PRINCIPLE SYSTEM DESIGN",
        14: "EXISTING PRINCIPLE SYSTEM",
    },
}


def page_count(pdf: Path) -> int:
    out = subprocess.run(["pdfinfo", str(pdf)], capture_output=True, text=True).stdout
    m = re.search(r"^Pages:\s+(\d+)", out, re.M)
    return int(m.group(1)) if m else 0

def normalise(line: str) -> str:
    """Repair display-font glyph substitutions.

    Cuttleswish's heading face maps capital I to the exclamation glyph, so
    pdftotext yields "DETAIL DES!GN". Only rewrite an exclamation mark that
    sits between two letters — a genuine "Wow!" is untouched.
    """
    return re.sub(r"(?<=[A-Za-z])!(?=[A-Za-z])", "I", line)


SECTION_RE = re.compile(r"^(\d{1,2})[.)]?\s+([A-Z][A-Za-z&/'\u2019\- ]{2,44})$")


def section_for(pdf: Path, page: int) -> tuple[int, str] | None:
    """Top-level numbered heading starting on this page, e.g. "2 Market analysis".

    Only the first few lines are considered — a section heading opens its
    page. Pages carrying two or more such headings are contents pages, not
    section starts, so they are skipped.
    """
    out = subprocess.run(
        ["pdftotext", "-f", str(page), "-l", str(page), str(pdf), "-"],
        capture_output=True, text=True,
    ).stdout
    hits = []
    for raw in out.splitlines()[:14]:
        m = SECTION_RE.match(" ".join(raw.split()))
        if m:
            hits.append((int(m.group(1)), normalise(m.group(2).strip())))
    if len(hits) != 1:
        return None
    return hits[0]


def title_for(pdf: Path, page: int) -> str | None:
    out = subprocess.run(
        ["pdftotext", "-f", str(page), "-l", str(page), str(pdf), "-"],
        capture_output=True, text=True,
    ).stdout
    for raw in out.splitlines():
        line = " ".join(raw.split())
        if not line or NOISE.match(line):
            continue
        if page > 1 and line.strip().lower() in BYLINES:
            continue
        # A heading: short, starts like a heading (capital / digit-free),
        # and is not a wrapped body-copy fragment.
        if not (2 <= len(line) <= 46):
            continue
        if line.endswith((",", ";", ".")) and not line.isupper():
            continue
        if not line[0].isupper():
            continue  # lowercase start = mid-sentence wrap
        words = line.split()
        if len(words) > 6:
            continue
        # Reject lines that read as prose (common lowercase connectives).
        if any(w.lower() in {"is", "are", "was", "the", "of", "and", "as", "for", "through"}
               for w in words[1:]) and not line.isupper():
            continue
        return normalise(line)
    return None

def main() -> None:
    lines = [
        "// AUTO-GENERATED by scripts/build-case-decks.sh + extract-deck-titles.py",
        "// — do not edit by hand.",
        "export type CaseDeck = {",
        "  label: string;",
        "  pages: number;",
        "  /** Compressed source PDF, rendered on-site by PDF.js. */",
        "  pdf: string;",
        "  /** Rasterised page dir (thumbnails / fallback). */",
        "  dir: string;",
        "  /** Section title per page, where one could be detected. */",
        "  titles: (string | null)[];",
        "  /** Set only on the page where a new numbered section begins. */",
        "  sections: (string | null)[];",
        "};",
        "",
        "export const CASE_DECKS: Record<string, CaseDeck> = {",
    ]
    existing = TS.read_text() if TS.exists() else ""
    for slug, rel in SOURCES.items():
        pdf = ROOT / rel
        if not pdf.exists():
            print(f"SKIP {slug} — missing {rel}")
            continue
        m = re.search(rf'"{re.escape(slug)}":\s*{{\s*label:\s*"([^"]+)"', existing)
        label = m.group(1) if m else "Document"
        n = page_count(pdf)
        titles = [title_for(pdf, i) for i in range(1, n + 1)]
        for page_no, fixed in OVERRIDES.get(slug, {}).items():
            if 1 <= page_no <= n:
                titles[page_no - 1] = fixed
        found = sum(1 for t in titles if t)

        # Section starts: accept a heading only when its number advances on
        # the last one accepted, which drops contents pages, repeats and
        # stray prose that happens to open with a digit.
        sections: list[str | None] = [None] * n
        last_no = 0
        for i in range(1, n + 1):
            hit = section_for(pdf, i)
            if hit and hit[0] > last_no:
                last_no = hit[0]
                sections[i - 1] = f"{hit[0]} {hit[1]}"
        n_sections = sum(1 for s in sections if s)

        # Not every deck numbers its sections. Cuttleswish, for one, sets a
        # plain heading at the top-left of each page and repeats it across
        # that section's pages — so fall back to the page titles and mark a
        # start wherever the heading CHANGES. Same result as the numbered
        # path: one index entry per section, carried across its pages.
        if n_sections < 2:
            sections = [None] * n
            previous = None
            for i, title in enumerate(titles):
                if title and title != previous:
                    sections[i] = title
                previous = title or previous
            n_sections = sum(1 for s in sections if s)
        rendered = ", ".join("null" if t is None else '"%s"' % t.replace('"', "'") for t in titles)
        rendered_sections = ", ".join(
            "null" if s is None else '"%s"' % s.replace('"', "'") for s in sections
        )
        lines.append(
            f'  "{slug}": {{ label: "{label}", pages: {n}, '
            f'pdf: "/case-pdf/{slug}.pdf", dir: "/case-pdf/{slug}", '
            f'titles: [{rendered}], sections: [{rendered_sections}] }},'
        )
        print(f"{slug}: {found}/{n} pages titled, {n_sections} sections")
    lines.append("};")
    TS.write_text("\n".join(lines) + "\n")
    print(f"wrote {TS.relative_to(ROOT)}")

main()
