#!/usr/bin/env python3
"""Pull a section title for each page of the deck PDFs using pdftotext,
and fold them into lib/case-decks.ts so the slideshow progress bar can
label real content sections instead of bare page numbers.

Heuristic: the first short, title-like line on each page. Pages with no
plausible heading fall back to null (the UI shows the page number).

Usage: python3 scripts/extract-deck-titles.py
"""
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TS = ROOT / "lib" / "case-decks.ts"

SOURCES = {
    "cardo": "raw-assets/cardo/project-work/Cardo - Business Report.pdf",
    "aid-sirho-frames": "raw-assets/aid/project-work/Rhodes_Sinai_Portfolio.pdf",
    "cuttleswish": "raw-assets/cuttleswish/project-work/IDE_Group4_Portfolio.pdf",
    "brushed-lips": "raw-assets/brushed-lips/project-work/SDE.pdf",
}

# Lines that are page furniture rather than section titles.
NOISE = re.compile(
    r"^(page\s*\d+|\d+|figure\s*\d+|fig\.?\s*\d+|contents|www\.|http)",
    re.I,
)

def page_count(pdf: Path) -> int:
    out = subprocess.run(["pdfinfo", str(pdf)], capture_output=True, text=True).stdout
    m = re.search(r"^Pages:\s+(\d+)", out, re.M)
    return int(m.group(1)) if m else 0

def normalise(line: str) -> str:
    """Repair display-font glyph substitutions.

    Cuttleswish's heading face maps capital I to the exclamation glyph, so
    pdftotext yields "DETAIL DES!GN". Only rewrite an exclamation mark that
    sits between two letters — a genuine "Wow!" is untouched.
    """
    return re.sub(r"(?<=[A-Za-z])!(?=[A-Za-z])", "I", line)


def title_for(pdf: Path, page: int) -> str | None:
    out = subprocess.run(
        ["pdftotext", "-f", str(page), "-l", str(page), str(pdf), "-"],
        capture_output=True, text=True,
    ).stdout
    for raw in out.splitlines():
        line = " ".join(raw.split())
        if not line or NOISE.match(line):
            continue
        # A heading: short, starts like a heading (capital / digit-free),
        # and is not a wrapped body-copy fragment.
        if not (2 <= len(line) <= 46):
            continue
        if line.endswith((",", ";", ".")) and not line.isupper():
            continue
        if not line[0].isupper():
            continue  # lowercase start = mid-sentence wrap
        words = line.split()
        if len(words) > 6:
            continue
        # Reject lines that read as prose (common lowercase connectives).
        if any(w.lower() in {"is", "are", "was", "the", "of", "and", "as", "for", "through"}
               for w in words[1:]) and not line.isupper():
            continue
        return normalise(line)
    return None

def main() -> None:
    lines = [
        "// AUTO-GENERATED by scripts/build-case-decks.sh + extract-deck-titles.py",
        "// — do not edit by hand.",
        "export type CaseDeck = {",
        "  label: string;",
        "  pages: number;",
        "  dir: string;",
        "  /** Section title per page, where one could be detected. */",
        "  titles: (string | null)[];",
        "};",
        "",
        "export const CASE_DECKS: Record<string, CaseDeck> = {",
    ]
    existing = TS.read_text() if TS.exists() else ""
    for slug, rel in SOURCES.items():
        pdf = ROOT / rel
        if not pdf.exists():
            print(f"SKIP {slug} — missing {rel}")
            continue
        m = re.search(rf'"{re.escape(slug)}":\s*{{\s*label:\s*"([^"]+)"', existing)
        label = m.group(1) if m else "Document"
        n = page_count(pdf)
        titles = [title_for(pdf, i) for i in range(1, n + 1)]
        found = sum(1 for t in titles if t)
        rendered = ", ".join("null" if t is None else '"%s"' % t.replace('"', "'") for t in titles)
        lines.append(
            f'  "{slug}": {{ label: "{label}", pages: {n}, '
            f'dir: "/case-pdf/{slug}", titles: [{rendered}] }},'
        )
        print(f"{slug}: {found}/{n} pages titled")
    lines.append("};")
    TS.write_text("\n".join(lines) + "\n")
    print(f"wrote {TS.relative_to(ROOT)}")

main()
